spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672                                    # 注意端口是5672，不是15672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

app:
  msg: this is test msg
  
zuul:
  routes:
    api-gateway: /gateway/**  #方式一
    gateway:
      path: /api-gateway/**   #方式二
      service-id: api-gateway