spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672                                    # 注意端口是5672，不是15672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true  #设置微服务调用地址为IP优先（缺省为false）
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}